config/routes.rb
ElasticSearchSample::Application.routes.draw do
  resources :jobs

  resources :users

  root to: "users#index"
end

app/models/job.rb
class Job < ActiveRecord::Base
  include Tire::Model::Search
  include Tire::Model::Callbacks
end

app/models/user.rb
class User < ActiveRecord::Base
  include Tire::Model::Search
  include Tire::Model::Callbacks

  # Tire uses dynamic mapping by default for indexing your data
  # If you want choose which data to index, you can do it by using the
  # mapping block below

  # Some quick description of different kind of analyzers
  # keyword = Indexes the whole field. Good for specific text like email, zipcode, phone number
  # standard = Grammar based tokenizer that is a good tokenizer for most European language documents
  # snowball = Stemming analyzer

  # Research links for analyzers
  # http://stackoverflow.com/questions/3875382/lucene-standard-analyzer-vs-snowball
  # http://stackoverflow.com/questions/9670016/how-do-i-set-the-default-analyzer-for-elastic-search-with-tire

  mapping do
    indexes :id,           type: 'integer' ,index: :not_analyzed

    # Boost increases priority when searching. Default value is 1.0
    indexes :first_name,   type: 'string'

    indexes :last_name,    type: 'string'
    indexes :email,        type: 'string'
  end

  # You can just use the default #search of Tire
  # Or you can override the method and make your own custom search

  def self.search(params)
    page = (params[:page] || 1).to_i
    per_page = 5

    # To use pagination, you can't pass the page and per_page inside the block
    # so we just declare it as a hash for default search arguments

    tire.search(page: page, per_page: per_page) do
      query { string params[:query] } if params[:query].present?

      # Types for filters available at
      # http://www.elasticsearch.org/guide/reference/query-dsl/
      filter :range, age: { lte: params[:age_filter].to_i } if params[:age_filter].present?
      filter :term, age:params[:age].to_i if params[:age].present?

      sort { by :age, 'asc' }
      facet 'ages' do
        # Kinds of facets: terms, range, histogram, date histogram, filter, query, statistical,
        # terms stats, geo distance

        # Show 5 highest results by age
        # Order options: count, term, reverse_count or reverse_term
        terms :age, size: 5, order: 'term'
      end

      # To add highlighting to results use the #highlight function
      # It accepts an array of symbols for field names

      highlight :first_name
      #highlight(:first_name, :last_name, :address, pre_tags: '<em>', post_tags: '</em>')

      #highlight do
      #  pre_tags ['<em>']
      #  post_tags ['</em>']
      #end
    end
  end

  def name
    "#{first_name} #{last_name}"
  end

  # If you want to add custom fields to the index use this method
  def to_indexed_json
    to_json(methods: [:name])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    if params[:query].present?
      @jobs = Job.search(params[:query], load: true, page: (params[:page] || 1), per_page: 30)
    else
      @jobs = Job.paginate(page: params[:page], per_page: 30)
    end
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render action: 'show', status: :created, location: @job }
      else
        format.html { render action: 'new' }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:job_title, :salary, :company, :skill, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    if params[:query].present? || params[:age_filter].present?
      # load: true => Pull records from AR and not just from ES
      # Fully compatible with will_paginate just add page option
      # @users = User.search(params[:query], load: true, page: (params[:page] || 1), per_page: 2)

      # When searching, you can use * for wildcard characters
      # Use [field_name]:query to do a specific search to a specific field
      # By default, searching "string1 string2" uses an OR operator
      # You can do "string1 AND string2" to require both strings to be present
      # You can also do "string1 NOT string2" to omit a word from the search results

      @users = User.search(params)
    else
      @users = User.paginate(page: params[:page], per_page: 30)
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :first_name, :last_name, :phone_number, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :job_title %><br />
    <%= f.text_field :job_title %>
  </div>
  <div class="field">
    <%= f.label :salary %><br />
    <%= f.text_field :salary %>
  </div>
  <div class="field">
    <%= f.label :company %><br />
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :client_name %><br />
    <%= f.text_field :client_name %>
  </div>
  <div class="field">
    <%= f.label :skill %><br />
    <%= f.text_field :skill %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :published_date %><br />
    <%= f.date_select :published_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<h1>Listing jobs</h1>

<%= form_tag jobs_path, :method => 'get' do %>
  <%= label_tag :query %>
  <%= text_field_tag :query, params[:query] %>
  <%= submit_tag :search %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Job title</th>
      <th>Salary</th>
      <th>Company</th>
      <th>Client Name</th>
      <th>Skill</th>
      <th>Description</th>
      <th>Published Date</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
    <tr>
      <td><%= job.job_title %></td>
      <td><%= job.salary %></td>
      <td><%= job.company %></td>
      <td><%= job.client_name %></td>
      <td><%= job.skill %></td>
      <td><%= job.description %></td>
      <td><%= job.published_date %></td>
      <td><%= link_to 'Show', job %></td>
      <td><%= link_to 'Edit', edit_job_path(job) %></td>
      <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= will_paginate @jobs %>

<%= link_to 'New Job', new_job_path %>

app/views/jobs/new.html.erb
<h1>New job</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Job title:</strong>
  <%= @job.job_title %>
</p>

<p>
  <strong>Salary:</strong>
  <%= @job.salary %>
</p>

<p>
  <strong>Company:</strong>
  <%= @job.company %>
</p>

<p>
  <strong>Description:</strong>
  <%= @job.description %>
</p>


<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ElasticSearchSample</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <p>
    <%= link_to 'User', users_path %> | <%= link_to 'Job', jobs_path %>
  </p>
<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br />
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :Age %><br />
    <%= f.text_field :age %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<%= form_tag users_path, :method => 'get' do %>
  <%= label_tag :query %>
  <%= text_field_tag :query, params[:query] %>
  <%= label_tag :age_filter %>
  <%= text_field_tag :age_filter, params[:age_filter] %>
  <%= submit_tag :search %>
<% end %>

<% if @users.try(:facets) %>
  <h3>Ages</h3>
  <ul>
    <% @users.facets['ages']['terms'].each do |facet| %>
      <li>
        <%= link_to_unless_current facet['term'], params.merge(age: facet['term']) %>
        <% if params[:age] == facet['term'].to_s %>
          (<%= link_to "remove", params.merge(age: nil) %>)
        <% else %>
          (<%= facet['count'] %>)
        <% end %>
      </li>
    <% end %>
  </ul>
<% end %>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Phone number</th>
      <th>Address</th>
      <th>Age</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= user.email %></td>
      <td><%= user.try(:highlight).nil? ? user.first_name : user.highlight.first_name[0].html_safe %></td>
      <td><%= user.last_name %></td>
      <td><%= user.phone_number %></td>
      <td><%= user.address %></td>
      <td><%= user.age %></td>
      <td><%= link_to 'Show', user %></td>
      <td><%= link_to 'Edit', edit_user_path(user) %></td>
      <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= will_paginate @users %>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @user.phone_number %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user.address %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>